project_id = "uwncpnveatbwnsgepjlb"

[functions.manychat-webhook]
verify_jwt = false

[functions.submit-cv]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.reset-admin]
verify_jwt = false

[functions.create-sales-team]
verify_jwt = false

[functions.assign-lead-round-robin]
verify_jwt = false

[functions.import-leads-excel]
verify_jwt = true

[functions.notify-sales-team]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.zkteco-webhook]
verify_jwt = false

[functions.send-deal-notification]
verify_jwt = true

[functions.send-attendance-report]
verify_jwt = true

[functions.send-daily-report-email]
verify_jwt = true

[functions.send-personal-sales-reports]
verify_jwt = false

[functions.import-contracts-excel]
verify_jwt = true

[functions.sync-to-trello]
verify_jwt = true

[functions.import-trello-leads]
verify_jwt = true

[functions.send-application-email]
verify_jwt = false

[functions.send-contract-email]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.sop-webhook]
verify_jwt = false

[functions.google-places-autocomplete]
verify_jwt = false

[functions.google-places-details]
verify_jwt = false

[functions.notify-transfer]
verify_jwt = false
